Fix for error - parentheses (#76)
Line 32 needs to be '@click.group()' not '@click.group' to avoid error on terminal command: overcast_to_sqlite/cli.py", line 38, in <module> @cli.command() AttributeError: 'function' object has no attribute 'command'